# Dockerfile en ./frontend
FROM node:14

# Configura el directorio de trabajo
WORKDIR /app

# Copia los archivos package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos de la aplicación
COPY . .

# Exponer el puerto que usará el servidor
EXPOSE 3000

# Comando de inicio
CMD ["npm", "start"]
