# backend/Dockerfile

# Imagen base de Python
FROM python:3.9

# Directorio de trabajo en el contenedor
WORKDIR /app

# Copiar y instalar dependencias
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Copiar la aplicación
COPY . .

# Exponer el puerto Flask (por defecto 5000)
EXPOSE 5000

# Comando para iniciar la aplicación
CMD ["flask", "run", "--host=0.0.0.0"]
